
      - name: Create Vector dir
        become: true
        file:
          path: /etc/vector
          state: directory
          mode: '0666'
      - name: Get Vector tar
        get_url:
          url: "https://packages.timber.io/vector/0.42.0/vector-0.42.0-x86_64-unknown-linux-musl.tar.gz"
          dest: "/home/centos/vector-0.42.0-x86_64-unknown-linux-musl.tar.gz"
      
  
      - name: Unarchive vector
        become: true
        unarchive:
          src: /home/centos/vector-0.42.0-x86_64-unknown-linux-musl.tar.gz
          dest: /etc/vector
          mode: '0666'
          remote_src: yes

     
      - name: Temp file
        become: true
        template:
          src: vector.yaml.j2
          dest: /etc/vector/vector.yaml
          mode: '0644'
          
        notify:
          - Restart Vector